name: Publish

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      working-directory: src
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      working-directory: src
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      working-directory: src
    - name: Push
      run: dotnet nuget push MediatR.Extensions.AttributedBehaviors.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      working-directory: src
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}